# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Basic Site Settings
locale                   : #"天津大学"
title                    : "Higher Chai的个人主页"
title_separator          : "-"
name                     : &name "Your Name"
description              : &description ""
url                      : https://HigherChai.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "HigherChai.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
# Site Author

author:
 # Biographic information
  name             : "Higher Chai"
  avatar           : "android-chrome-512x512.png"
  bio              :  "每天就是扫扫地啊，念念经啊！"
  location         :  "Nankai District, Tianjin"
  email            :  "3109096638@qq.com"
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    :  
  employer         : "Peiyang university"
  researchgate     :  
  uri              : 
  bitbucket        : # Username
  codepen          : # Username
  dribbble         : # Username
  flickr           : # Username
  facebook         : # Username
  foursquare       : # Username
  github           : #"academicpages"
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  impactstory      : # Username
  lastfm           : # Username
  linkedin         : # Username
  dblp             : # Username
  orcid            : "https://orcid.org/0009-0006-3481-8048"
  pinterest        : # Username
  soundcloud       : # Username
  stackoverflow    : # Username
  steam            : # Username
  tumblr           : # Username
  twitter          : # Username
  vine             : # Username
  weibo            : # Username
  xing             : # Username
  youtube          : # Username
  wikipedia        : # Username


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
